### ISSUE TITLE
Display line number and symbol on the same line

### ISSUE THREAD

**Issue by gruzzlymug** [atom/symbols-view#129]
I'd like to get a more compact view of the symbols in the scrollable list. There is a lot of empty space to the right of the symbol and line number in the display in the list. I'd like to be able to see more symbols at once (in the same amount of space).

I think the file I'd like to modify is file-view.coffee. I could not find a way to change it locally. Is there a simple way to do this?

Thanks for making such a useful package.

**Comment by thedaniel** [comment]
You can style that in your own `styles.less` file - you'll have to play around a bit to get it the way you want, but these selectors should get you started:

```less
.symbols-view {
  .two-lines {
    .primary-line {
    }
    .secondary-line {
    }
  }
}
```

cc @simurai in case he has feedback on this, but I don't think we'll change the default view of the symbols to one line.

**Comment by simurai** [comment]
This should make it one line only:

```less
.symbols-view {
  .two-lines {
    display: flex !important;
    .primary-line {
      flex: 1;
    }
    .secondary-line {
    }
  }
}
```

![screen shot 2015-10-28 at 12 54 35 am](https://cloud.githubusercontent.com/assets/378023/10763833/d345219e-7d0e-11e5-9838-a5c202995ffd.png)
